// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/confus1on/meetmeup/ent/meetups"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Meetups is the model entity for the Meetups schema.
type Meetups struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// UsersID holds the value of the "usersID" field.
	UsersID int `json:"usersID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MeetupsQuery when eager-loading is set.
	Edges MeetupsEdges `json:"edges"`
}

// MeetupsEdges holds the relations/edges for other nodes in the graph.
type MeetupsEdges struct {
	// User holds the value of the user edge.
	User []*Users
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Meetups) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
		&sql.NullString{}, // description
		&sql.NullInt64{},  // usersID
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Meetups fields.
func (m *Meetups) assignValues(values ...interface{}) error {
	if m, n := len(values), len(meetups.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	m.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		m.Name = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field description", values[1])
	} else if value.Valid {
		m.Description = value.String
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field usersID", values[2])
	} else if value.Valid {
		m.UsersID = int(value.Int64)
	}
	return nil
}

// QueryUser queries the user edge of the Meetups.
func (m *Meetups) QueryUser() *UsersQuery {
	return (&MeetupsClient{m.config}).QueryUser(m)
}

// Update returns a builder for updating this Meetups.
// Note that, you need to call Meetups.Unwrap() before calling this method, if this Meetups
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Meetups) Update() *MeetupsUpdateOne {
	return (&MeetupsClient{m.config}).UpdateOne(m)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (m *Meetups) Unwrap() *Meetups {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Meetups is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Meetups) String() string {
	var builder strings.Builder
	builder.WriteString("Meetups(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteString(", name=")
	builder.WriteString(m.Name)
	builder.WriteString(", description=")
	builder.WriteString(m.Description)
	builder.WriteString(", usersID=")
	builder.WriteString(fmt.Sprintf("%v", m.UsersID))
	builder.WriteByte(')')
	return builder.String()
}

// MeetupsSlice is a parsable slice of Meetups.
type MeetupsSlice []*Meetups

func (m MeetupsSlice) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
