// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/confus1on/meetmeup/ent/meetups"
	"github.com/confus1on/meetmeup/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// MeetupsDelete is the builder for deleting a Meetups entity.
type MeetupsDelete struct {
	config
	predicates []predicate.Meetups
}

// Where adds a new predicate to the delete builder.
func (md *MeetupsDelete) Where(ps ...predicate.Meetups) *MeetupsDelete {
	md.predicates = append(md.predicates, ps...)
	return md
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (md *MeetupsDelete) Exec(ctx context.Context) (int, error) {
	return md.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (md *MeetupsDelete) ExecX(ctx context.Context) int {
	n, err := md.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (md *MeetupsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: meetups.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: meetups.FieldID,
			},
		},
	}
	if ps := md.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, md.driver, _spec)
}

// MeetupsDeleteOne is the builder for deleting a single Meetups entity.
type MeetupsDeleteOne struct {
	md *MeetupsDelete
}

// Exec executes the deletion query.
func (mdo *MeetupsDeleteOne) Exec(ctx context.Context) error {
	n, err := mdo.md.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{meetups.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mdo *MeetupsDeleteOne) ExecX(ctx context.Context) {
	mdo.md.ExecX(ctx)
}
