// Code generated by entc, DO NOT EDIT.

package meetups

const (
	// Label holds the string label denoting the meetups type in the database.
	Label = "meetups"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description"
	// FieldUsersID holds the string denoting the usersid vertex property in the database.
	FieldUsersID = "users_id"

	// Table holds the table name of the meetups in the database.
	Table = "meetups"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "users"
	// UserInverseTable is the table name for the Users entity.
	// It exists in this package in order to avoid circular dependency with the "users" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "meetups_user_id"
)

// Columns holds all SQL columns for meetups fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldUsersID,
}
