// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Meetups is the predicate function for meetups builders.
type Meetups func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
